### ISSUE TITLE
Problem with the render textures?

### ISSUE THREAD

**Issue by Jskallio** [lukis101/ParticleCloudVRC#1]
Hi, for some reason this effect works fine in unity, but when uploaded to vrchat all dots starts going to one direction. Same happens in unity if you put the strength to 0. Could it be that the vrchat messes up the render textures and the data is not transmitted correctly. I noticed same kind of problems when I tried making color changing avatar with a camera and render texture.
PS. love the effect

**Comment by lukis101** [comment]
Is the prefab still intact - maybe changed the hierarchy of pivots? Had one similar report but happened also in editor

**Comment by Jskallio** [comment]
I didnt change anything in hierarchy. Activating the effect and reset works just fine, only problem is that the attraction  doesnt get delivered. Here is a picture of my current hierarchy: https://i.imgur.com/8FjptpF.jpg

**Comment by lukis101** [comment]
Maybe there's some scaling probems or or material properties mismatch as in-game, properties in animation clips will override the ones on actual material (which don't get reset after exiting play mode). Check if all frame keypoints are correct if they were modified. Dont forget to set strength of both pivot materials to 0.
If still have problems, setting it up on a tutorial avatar and uploading .unitypackage would help in troubleshooting

**Comment by Jskallio** [comment]
it was a scale problem! My avatar was scaled down to 0.5 which caused the problem. Thanks a lot for the help!
